### ISSUE TITLE
Change to local result directory

### ISSUE THREAD

**Issue by leondavi** [leondavi/NErlNet#158]
@halfway258 

https://github.com/leondavi/NErlNet/blob/1581734552b78696164860d4d887f34b83ab341d/src_py/apiServer/apiServer.py#L159

**Comment by leondavi** [comment]
@halfway258 
What is this issue? I can't remember?
Can we close it?

**Comment by halfway258** [comment]
You were not happy that results were saved locally. I think its fine, but we may want to add a way to specify a results directory similarly to the inputData directory

**Comment by leondavi** [comment]
Branch onn6 contains a new config directory with *.nerlconfig files 
You can add it there and read a result_path.nerlconfig file 
https://github.com/leondavi/NErlNet/pull/161
