### ISSUE TITLE
CI - Node. is 16 actions are deprecated.

### ISSUE THREAD

**Issue by leondavi** [leondavi/NErlNet#290]
@dolby360 if you can please assist us with this warning of Node.js 16 deprecated.

![image](https://github.com/leondavi/NErlNet/assets/18975070/0ef001f2-1edf-4987-9f86-e1fbbd44a103)

https://github.com/leondavi/NErlNet/actions/runs/8241275327/attempts/1?pr=286

**Comment by dolby360** [comment]
@leondavi no problem

**Comment by leondavi** [comment]
Thanks!
