### ISSUE TITLE
openNN printing problem

### ISSUE THREAD

**Issue by evgenyan95** [leondavi/NErlNet#86]
OpenNN's perform_training() command prints undesired outputs.
We should find a way to disable those prints.
![Screenshot from 2022-04-04 17-27-30](https://user-images.githubusercontent.com/88283837/161567626-476a1d07-7554-4e90-b5da-5fb53995d283.png)
.

**Comment by leondavi** [comment]
https://github.com/Artelnics/opennn/issues/220

**Comment by leondavi** [comment]
> [Artelnics/opennn#220](https://github.com/Artelnics/opennn/issues/220)

Update - training_strategy.set_display(false);
